"""empty message

Revision ID: b123f63b8811
Revises: 
Create Date: 2025-06-03 10:05:57.925091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b123f63b8811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index(op.f('ix_attendance_clock_in'), 'attendance', ['clock_in'], unique=False)
    op.create_index(op.f('ix_attendance_clock_out'), 'attendance', ['clock_out'], unique=False)
    op.create_index(op.f('ix_attendance_created_at'), 'attendance', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_updated_at'), 'attendance', ['updated_at'], unique=False)
    op.create_table('leave_request',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('leave_id')
    )
    op.create_index(op.f('ix_leave_request_created_at'), 'leave_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_leave_request_end_date'), 'leave_request', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_request_start_date'), 'leave_request', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_request_updated_at'), 'leave_request', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_request_updated_at'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_start_date'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_end_date'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_created_at'), table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_index(op.f('ix_attendance_updated_at'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_created_at'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_clock_out'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_clock_in'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
