"""empty message

Revision ID: 01daa9ddf427
Revises: 
Create Date: 2025-06-03 09:53:10.392766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01daa9ddf427'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invited__users',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('invite_id'),
    schema='public'
    )
    with op.batch_alter_table('invited__users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_invited__users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_invited__users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_invited__users_updated_at'), ['updated_at'], unique=False)

    op.create_table('organization',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=240), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('organization_code', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    schema='public'
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_organization_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_organization_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_organization_organization_code'), ['organization_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_organization_organization_name'), ['organization_name'], unique=False)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_public_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_user_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_organization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organization.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organization', schema='public')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_public_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_public_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_public_user_email'))
        batch_op.drop_index(batch_op.f('ix_public_user_created_at'))

    op.drop_table('user', schema='public')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_organization_organization_name'))
        batch_op.drop_index(batch_op.f('ix_public_organization_organization_code'))
        batch_op.drop_index(batch_op.f('ix_public_organization_created_at'))
        batch_op.drop_index(batch_op.f('ix_public_organization_country'))

    op.drop_table('organization', schema='public')
    with op.batch_alter_table('invited__users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_invited__users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_public_invited__users_email'))
        batch_op.drop_index(batch_op.f('ix_public_invited__users_created_at'))

    op.drop_table('invited__users', schema='public')
    # ### end Alembic commands ###
